export const SET_DISPLAY = 'SET_DISPLAY'
export const SET_BREAKPOINTS = 'SET_BREAKPOINTS'
export const SET_MENU_VISIBILITY = 'SET_MENU_VISIBILITY'
export const SET_DETAIL_VISIBILITY = 'SET_DETAIL_VISIBILITY'
